#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse
import pandas as pd

# Import from test_pro
import test_pro
from test_pro.lib import clean_data
from test_pro.lib import try_me
if __name__ == '__main__':
    usage = '%(prog)s'
    description = 'test_pro_description'
    # https://docs.python.org/3/library/argparse.html
    # https://docs.python.org/3/howto/argparse.html
    parser = argparse.ArgumentParser(description=description, usage=usage)
    args = parser.parse_args()
    folder_source, _ = split(test_pro.__file__)
    df = pd.read_csv('{}/data/data.csv.gz'.format(folder_source))
    print('  test_pro/data/data.csv.gz Loaded')

    res = clean_data(df)
    res.to_csv('out.csv', index=False)
    print('==> out.csv MADE ')
    print('    shape is {}'.format(res.shape))
    try_me()
